begin;

create table if not exists public.grid_lottery_sets (
    id bigint generated by default as identity primary key,
    owner_id uuid not null
        references public.profiles(id)
        on delete cascade,
    name text not null,
    language_id bigint not null
        references public.languages(id),
    display_mode text not null
        check (
            display_mode in (
                'image-text',
                'image',
                'text'
            )
        ),
    custom_items text[] not null
        default '{}'::text[],
    active boolean not null
        default true,
    created_at timestamptz not null
        default now(),
    updated_at timestamptz not null
        default now()
);

create table if not exists public.grid_lottery_set_items (
    id bigint generated by default as identity primary key,
    set_id bigint not null
        references public.grid_lottery_sets(id)
        on delete cascade,
    item_id bigint not null
        references public.items(id)
        on delete cascade,
    position smallint not null,
    created_at timestamptz not null
        default now(),
    unique (set_id, item_id),
    unique (set_id, position)
);

create unique index if not exists
    grid_lottery_sets_unique_owner_name
on public.grid_lottery_sets (
    owner_id,
    lower(trim(name))
)
where active = true;

alter table public.grid_lottery_sets
    enable row level security;

alter table public.grid_lottery_set_items
    enable row level security;

drop policy if exists
    "Users can read their Grid Lottery sets"
on public.grid_lottery_sets;

create policy
    "Users can read their Grid Lottery sets"
on public.grid_lottery_sets
for select
to authenticated
using (
    owner_id = auth.uid()
);

drop policy if exists
    "Users can read their Grid Lottery set items"
on public.grid_lottery_set_items;

create policy
    "Users can read their Grid Lottery set items"
on public.grid_lottery_set_items
for select
to authenticated
using (
    exists (
        select 1
        from public.grid_lottery_sets
        where grid_lottery_sets.id =
            grid_lottery_set_items.set_id
          and grid_lottery_sets.owner_id =
            auth.uid()
    )
);

create or replace function public.save_grid_lottery_set(
    input_name text,
    input_language_id bigint,
    input_display_mode text,
    input_item_ids bigint[],
    input_custom_items text[]
)
returns public.grid_lottery_sets
language plpgsql
security definer
set search_path = ''
as $function$
declare
    current_user_id uuid;
    clean_name text;
    clean_custom_items text[];
    clean_item_ids bigint[];
    total_item_count integer;
    valid_item_count integer;
    saved_set public.grid_lottery_sets;
    free_limit integer;
begin
    current_user_id := auth.uid();

    if current_user_id is null
       or coalesce(
            (auth.jwt() ->> 'is_anonymous')::boolean,
            false
       ) then
        raise exception
            'Log in with a regular account to save Grid Lottery sets.';
    end if;

    clean_name := trim(input_name);

    if clean_name = ''
       or char_length(clean_name) > 80 then
        raise exception
            'Enter a Grid Lottery Set name of 1 to 80 characters.';
    end if;

    if input_display_mode not in (
        'image-text',
        'image',
        'text'
    ) then
        raise exception
            'The Grid Lottery display mode is invalid.';
    end if;

    if not exists (
        select 1
        from public.languages
        where id = input_language_id
    ) then
        raise exception
            'The selected language is not available.';
    end if;

    select coalesce(
        array_agg(value order by position),
        '{}'::text[]
    )
    into clean_custom_items
    from (
        select
            trim(entry.value) as value,
            min(entry.ordinality) as position
        from unnest(
            coalesce(
                input_custom_items,
                '{}'::text[]
            )
        ) with ordinality as entry(value, ordinality)
        where trim(entry.value) <> ''
          and char_length(trim(entry.value)) <= 100
        group by lower(trim(entry.value)), trim(entry.value)
    ) cleaned_custom_items;

    select coalesce(
        array_agg(item_id order by position),
        '{}'::bigint[]
    )
    into clean_item_ids
    from (
        select
            entry.item_id,
            min(entry.ordinality) as position
        from unnest(
            coalesce(
                input_item_ids,
                '{}'::bigint[]
            )
        ) with ordinality as entry(item_id, ordinality)
        group by entry.item_id
    ) cleaned_item_ids;

    total_item_count :=
        cardinality(clean_item_ids) +
        cardinality(clean_custom_items);

    if total_item_count < 2 then
        raise exception
            'Choose or enter at least two items.';
    end if;

    if total_item_count > 50 then
        raise exception
            'A Grid Lottery Set can contain at most 50 items.';
    end if;

    select count(*)
    into valid_item_count
    from public.items
    where id = any(clean_item_ids)
      and active = true;

    if valid_item_count <>
        cardinality(clean_item_ids) then
        raise exception
            'One or more selected library items are unavailable.';
    end if;

    if exists (
        select 1
        from public.grid_lottery_sets
        where owner_id = current_user_id
          and active = true
          and lower(trim(name)) =
              lower(clean_name)
    ) then
        raise exception
            'You already have a Grid Lottery Set with this name.';
    end if;

    if not public.user_has_premium() then
        free_limit :=
            public.get_free_saved_game_limit();

        if (
            select count(*)
            from public.grid_lottery_sets
            where owner_id = current_user_id
              and active = true
        ) >= free_limit then
            raise exception
                'Free accounts can save up to % Grid Lottery Sets. Delete one or upgrade to Premium.',
                free_limit;
        end if;
    end if;

    insert into public.grid_lottery_sets (
        owner_id,
        name,
        language_id,
        display_mode,
        custom_items
    )
    values (
        current_user_id,
        clean_name,
        input_language_id,
        input_display_mode,
        clean_custom_items
    )
    returning *
    into saved_set;

    insert into public.grid_lottery_set_items (
        set_id,
        item_id,
        position
    )
    select
        saved_set.id,
        item_id,
        ordinality::smallint
    from unnest(clean_item_ids)
        with ordinality as selected_item(
            item_id,
            ordinality
        );

    return saved_set;
end;
$function$;

create or replace function public.update_grid_lottery_set(
    input_set_id bigint,
    input_name text,
    input_language_id bigint,
    input_display_mode text,
    input_item_ids bigint[],
    input_custom_items text[]
)
returns public.grid_lottery_sets
language plpgsql
security definer
set search_path = ''
as $function$
declare
    current_user_id uuid;
    clean_name text;
    clean_custom_items text[];
    clean_item_ids bigint[];
    total_item_count integer;
    valid_item_count integer;
    updated_set public.grid_lottery_sets;
begin
    current_user_id := auth.uid();

    if current_user_id is null
       or coalesce((auth.jwt() ->> 'is_anonymous')::boolean, false) then
        raise exception 'Log in with a regular account to edit Grid Lottery sets.';
    end if;

    clean_name := trim(input_name);

    if clean_name = '' or char_length(clean_name) > 80 then
        raise exception 'Enter a Grid Lottery Set name of 1 to 80 characters.';
    end if;

    if input_display_mode not in ('image-text', 'image', 'text') then
        raise exception 'The Grid Lottery display mode is invalid.';
    end if;

    if not exists (
        select 1 from public.languages where id = input_language_id
    ) then
        raise exception 'The selected language is not available.';
    end if;

    select coalesce(array_agg(value order by position), '{}'::text[])
    into clean_custom_items
    from (
        select trim(entry.value) as value, min(entry.ordinality) as position
        from unnest(coalesce(input_custom_items, '{}'::text[]))
            with ordinality as entry(value, ordinality)
        where trim(entry.value) <> ''
          and char_length(trim(entry.value)) <= 100
        group by lower(trim(entry.value)), trim(entry.value)
    ) cleaned_custom_items;

    select coalesce(array_agg(item_id order by position), '{}'::bigint[])
    into clean_item_ids
    from (
        select entry.item_id, min(entry.ordinality) as position
        from unnest(coalesce(input_item_ids, '{}'::bigint[]))
            with ordinality as entry(item_id, ordinality)
        group by entry.item_id
    ) cleaned_item_ids;

    total_item_count := cardinality(clean_item_ids) + cardinality(clean_custom_items);

    if total_item_count < 2 then
        raise exception 'Choose or enter at least two items.';
    end if;

    if total_item_count > 50 then
        raise exception 'A Grid Lottery Set can contain at most 50 items.';
    end if;

    select count(*)
    into valid_item_count
    from public.items
    where id = any(clean_item_ids)
      and active = true;

    if valid_item_count <> cardinality(clean_item_ids) then
        raise exception 'One or more selected library items are unavailable.';
    end if;

    if exists (
        select 1
        from public.grid_lottery_sets
        where owner_id = current_user_id
          and active = true
          and id <> input_set_id
          and lower(trim(name)) = lower(clean_name)
    ) then
        raise exception 'You already have a Grid Lottery Set with this name.';
    end if;

    update public.grid_lottery_sets
    set
        name = clean_name,
        language_id = input_language_id,
        display_mode = input_display_mode,
        custom_items = clean_custom_items,
        updated_at = now()
    where id = input_set_id
      and owner_id = current_user_id
      and active = true
    returning * into updated_set;

    if updated_set.id is null then
        raise exception 'This Grid Lottery Set could not be edited.';
    end if;

    delete from public.grid_lottery_set_items
    where set_id = input_set_id;

    insert into public.grid_lottery_set_items (set_id, item_id, position)
    select input_set_id, item_id, ordinality::smallint
    from unnest(clean_item_ids)
        with ordinality as selected_item(item_id, ordinality);

    return updated_set;
end;
$function$;

create or replace function public.delete_grid_lottery_set(
    input_set_id bigint
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $function$
declare
    deleted_set_id bigint;
begin
    delete from public.grid_lottery_sets
    where id = input_set_id
      and owner_id = auth.uid()
    returning id
    into deleted_set_id;

    if deleted_set_id is null then
        raise exception
            'This Grid Lottery Set could not be deleted.';
    end if;

    return deleted_set_id;
end;
$function$;

revoke all on function public.save_grid_lottery_set(
    text,
    bigint,
    text,
    bigint[],
    text[]
) from public;

revoke all on function public.delete_grid_lottery_set(
    bigint
) from public;

revoke all on function public.update_grid_lottery_set(
    bigint,
    text,
    bigint,
    text,
    bigint[],
    text[]
) from public;

grant execute on function public.save_grid_lottery_set(
    text,
    bigint,
    text,
    bigint[],
    text[]
) to authenticated;

grant execute on function public.delete_grid_lottery_set(
    bigint
) to authenticated;

grant execute on function public.update_grid_lottery_set(
    bigint,
    text,
    bigint,
    text,
    bigint[],
    text[]
) to authenticated;

grant select on public.grid_lottery_sets
to authenticated;

grant select on public.grid_lottery_set_items
to authenticated;

commit;
