begin;

create table if not exists public.claim_grid_sets (
    id bigint generated by default as identity primary key,
    owner_id uuid not null
        references public.profiles(id)
        on delete cascade,
    name text not null,
    team_count smallint not null
        check (team_count between 2 and 4),
    question_timer smallint not null
        check (question_timer in (10, 20, 30, 40, 50, 60)),
    team_colors text[] not null,
    is_public boolean not null default false,
    share_slug text,
    active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    check (cardinality(team_colors) = team_count)
);

create table if not exists public.claim_grid_questions (
    id bigint generated by default as identity primary key,
    set_id bigint not null
        references public.claim_grid_sets(id)
        on delete cascade,
    position smallint not null
        check (position between 1 and 50),
    question_text text,
    question_item_id bigint
        references public.items(id)
        on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (set_id, position),
    check (
        nullif(trim(question_text), '') is not null
        or question_item_id is not null
    )
);

create table if not exists public.claim_grid_choices (
    id bigint generated by default as identity primary key,
    question_id bigint not null
        references public.claim_grid_questions(id)
        on delete cascade,
    position smallint not null
        check (position between 1 and 4),
    answer_text text,
    answer_item_id bigint
        references public.items(id)
        on delete set null,
    is_correct boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (question_id, position),
    check (
        nullif(trim(answer_text), '') is not null
        or answer_item_id is not null
    )
);

create unique index if not exists
    claim_grid_sets_unique_owner_name
on public.claim_grid_sets (
    owner_id,
    lower(trim(name))
)
where active = true;

create unique index if not exists
    claim_grid_sets_unique_share_slug
on public.claim_grid_sets (share_slug)
where share_slug is not null;

create unique index if not exists
    claim_grid_choices_one_correct_answer
on public.claim_grid_choices (question_id)
where is_correct = true;

alter table public.claim_grid_sets
    enable row level security;

alter table public.claim_grid_questions
    enable row level security;

alter table public.claim_grid_choices
    enable row level security;

drop policy if exists
    "Users can read their Claim the Grid sets"
on public.claim_grid_sets;

create policy
    "Users can read their Claim the Grid sets"
on public.claim_grid_sets
for select
to authenticated
using (owner_id = auth.uid());

drop policy if exists
    "Users can read their Claim the Grid questions"
on public.claim_grid_questions;

create policy
    "Users can read their Claim the Grid questions"
on public.claim_grid_questions
for select
to authenticated
using (
    exists (
        select 1
        from public.claim_grid_sets
        where claim_grid_sets.id =
            claim_grid_questions.set_id
          and claim_grid_sets.owner_id = auth.uid()
    )
);

drop policy if exists
    "Users can read their Claim the Grid choices"
on public.claim_grid_choices;

create policy
    "Users can read their Claim the Grid choices"
on public.claim_grid_choices
for select
to authenticated
using (
    exists (
        select 1
        from public.claim_grid_questions
        join public.claim_grid_sets
          on claim_grid_sets.id =
             claim_grid_questions.set_id
        where claim_grid_questions.id =
            claim_grid_choices.question_id
          and claim_grid_sets.owner_id = auth.uid()
    )
);

revoke all on public.claim_grid_sets from anon;
revoke all on public.claim_grid_questions from anon;
revoke all on public.claim_grid_choices from anon;

revoke insert, update, delete
on public.claim_grid_sets
from authenticated;

revoke insert, update, delete
on public.claim_grid_questions
from authenticated;

revoke insert, update, delete
on public.claim_grid_choices
from authenticated;

grant select on public.claim_grid_sets to authenticated;
grant select on public.claim_grid_questions to authenticated;
grant select on public.claim_grid_choices to authenticated;

commit;
