begin;

create table if not exists public.claim_grid_sessions (
    id uuid primary key default gen_random_uuid(),
    host_id uuid not null
        references public.profiles(id)
        on delete cascade,
    source_set_id bigint
        references public.claim_grid_sets(id)
        on delete set null,
    room_code text not null unique,
    name text not null,
    status text not null default 'lobby'
        check (status in ('lobby', 'active', 'finished')),
    team_count smallint not null
        check (team_count between 2 and 4),
    game_duration_minutes smallint not null default 10
        check (game_duration_minutes in (3, 5, 7, 10, 15)),
    territory_timer smallint not null default 10
        check (territory_timer = 10),
    team_colors text[] not null,
    grid_size smallint not null
        check (grid_size in (5, 7, 9)),
    current_question_position smallint not null default 0,
    created_at timestamptz not null default now(),
    started_at timestamptz,
    ended_at timestamptz,
    expires_at timestamptz not null default (now() + interval '24 hours'),
    updated_at timestamptz not null default now(),
    check (cardinality(team_colors) = team_count)
);

create table if not exists public.claim_grid_teams (
    id bigint generated by default as identity primary key,
    session_id uuid not null
        references public.claim_grid_sessions(id)
        on delete cascade,
    team_number smallint not null
        check (team_number between 1 and 4),
    color text not null,
    created_at timestamptz not null default now(),
    unique (session_id, team_number)
);

create table if not exists public.claim_grid_players (
    id uuid primary key default gen_random_uuid(),
    session_id uuid not null
        references public.claim_grid_sessions(id)
        on delete cascade,
    user_id uuid not null
        references auth.users(id)
        on delete cascade,
    team_number smallint not null
        check (team_number between 1 and 4),
    display_name text not null,
    is_connected boolean not null default true,
    joined_at timestamptz not null default now(),
    last_seen_at timestamptz not null default now(),
    unique (session_id, user_id)
);

create unique index if not exists
    claim_grid_players_unique_room_name
on public.claim_grid_players (
    session_id,
    lower(trim(display_name))
);

create table if not exists public.claim_grid_session_questions (
    id bigint generated by default as identity primary key,
    session_id uuid not null
        references public.claim_grid_sessions(id)
        on delete cascade,
    position smallint not null
        check (position between 1 and 50),
    question_text text,
    question_item_id bigint
        references public.items(id)
        on delete set null,
    created_at timestamptz not null default now(),
    unique (session_id, position),
    check (
        nullif(trim(question_text), '') is not null
        or question_item_id is not null
    )
);

create table if not exists public.claim_grid_session_choices (
    id bigint generated by default as identity primary key,
    question_id bigint not null
        references public.claim_grid_session_questions(id)
        on delete cascade,
    position smallint not null
        check (position between 1 and 4),
    answer_text text,
    answer_item_id bigint
        references public.items(id)
        on delete set null,
    is_correct boolean not null default false,
    created_at timestamptz not null default now(),
    unique (question_id, position),
    check (
        nullif(trim(answer_text), '') is not null
        or answer_item_id is not null
    )
);

create unique index if not exists
    claim_grid_session_choices_one_correct
on public.claim_grid_session_choices (question_id)
where is_correct = true;

create table if not exists public.claim_grid_cells (
    id bigint generated by default as identity primary key,
    session_id uuid not null
        references public.claim_grid_sessions(id)
        on delete cascade,
    row_number smallint not null,
    column_number smallint not null,
    owner_team_number smallint
        check (owner_team_number between 1 and 4),
    base_team_number smallint
        check (base_team_number between 1 and 4),
    is_base boolean not null default false,
    captured_at timestamptz,
    updated_at timestamptz not null default now(),
    unique (session_id, row_number, column_number),
    check (
        (is_base = false and base_team_number is null)
        or
        (is_base = true and base_team_number is not null
         and owner_team_number = base_team_number)
    )
);

create table if not exists public.claim_grid_answers (
    id bigint generated by default as identity primary key,
    session_id uuid not null
        references public.claim_grid_sessions(id)
        on delete cascade,
    question_id bigint not null
        references public.claim_grid_session_questions(id)
        on delete cascade,
    player_id uuid not null
        references public.claim_grid_players(id)
        on delete cascade,
    choice_id bigint not null
        references public.claim_grid_session_choices(id)
        on delete cascade,
    is_correct boolean not null,
    answered_at timestamptz not null default now(),
    unique (question_id, player_id)
);

create table if not exists public.claim_grid_claim_votes (
    id bigint generated by default as identity primary key,
    session_id uuid not null
        references public.claim_grid_sessions(id)
        on delete cascade,
    question_id bigint not null
        references public.claim_grid_session_questions(id)
        on delete cascade,
    player_id uuid not null
        references public.claim_grid_players(id)
        on delete cascade,
    cell_id bigint not null
        references public.claim_grid_cells(id)
        on delete cascade,
    priority smallint not null
        check (priority between 1 and 3),
    created_at timestamptz not null default now(),
    unique (question_id, player_id, priority),
    unique (question_id, player_id, cell_id)
);

create table if not exists public.claim_grid_round_captures (
    id bigint generated by default as identity primary key,
    session_id uuid not null
        references public.claim_grid_sessions(id)
        on delete cascade,
    question_id bigint not null
        references public.claim_grid_session_questions(id)
        on delete cascade,
    team_number smallint not null
        check (team_number between 1 and 4),
    cell_id bigint not null
        references public.claim_grid_cells(id)
        on delete cascade,
    captured_at timestamptz not null default now(),
    unique (question_id, team_number)
);

alter table public.claim_grid_sessions enable row level security;
alter table public.claim_grid_teams enable row level security;
alter table public.claim_grid_players enable row level security;
alter table public.claim_grid_session_questions enable row level security;
alter table public.claim_grid_session_choices enable row level security;
alter table public.claim_grid_cells enable row level security;
alter table public.claim_grid_answers enable row level security;
alter table public.claim_grid_claim_votes enable row level security;
alter table public.claim_grid_round_captures enable row level security;

revoke all on public.claim_grid_sessions from anon, authenticated;
revoke all on public.claim_grid_teams from anon, authenticated;
revoke all on public.claim_grid_players from anon, authenticated;
revoke all on public.claim_grid_session_questions from anon, authenticated;
revoke all on public.claim_grid_session_choices from anon, authenticated;
revoke all on public.claim_grid_cells from anon, authenticated;
revoke all on public.claim_grid_answers from anon, authenticated;
revoke all on public.claim_grid_claim_votes from anon, authenticated;
revoke all on public.claim_grid_round_captures from anon, authenticated;

commit;
